version: "3.9"
services: 
  my-mysql:
    container_name: mysql-server
    image: mysql:5.7
    volumes: 
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "0000"
# services: 
#   django:
#     command: bash
#     container_name: mydjango
#     depends_on: 
#       - mysql
#     stdin_open: true
#     tty: true
#     image: ubuntu:16.04
#     ports:
#       - "7000:8000"

#   mysql:
#     command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
#     container_name: mysql
#     environment: 
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: "admin"
#       MYSQL_PASSWORD: "0000"
#     image: mysql:5.7
#     volumes: 
#       - ./mysql-data:/var/lib/mysql
#     ports: 
#       - "7001:3306"
