version: "3.9"
services: 
  my-mysql:
    container_name: mysql_server
    image: edowon0623/mymysql:1.2
    ports: 
      - 3306:3306
  my-django:
    container_name: django_server
    image: edowon0623/mydjango
    ports:
      - 8000:8000
    depends_on: 
      - my-mysql
    networks:
      - my-network
networks:
  my-network:
